const app=window.APP, data=window.DATA;
const $=id=>document.getElementById(id), svgNS='http://www.w3.org/2000/svg';
const escapeHtml=s=>String(s).replace(/[&<>"']/g,c=>({'&':'&amp;','<':'&lt;','>':'&gt;','"':'&quot;',"'":'&#39;'}[c]));
const fmt=(n,type='number')=>type==='currency'?'$'+n.toLocaleString('en-US',{maximumFractionDigits:0}):type==='currencyExact'?'$'+n.toLocaleString('en-US',{minimumFractionDigits:2,maximumFractionDigits:2}):type==='percent'?(n*100).toFixed(1)+'%':n.toLocaleString('en-US',{maximumFractionDigits:1});
function init(){document.title=app.title;$('title').textContent=app.title;$('subtitle').textContent=app.subtitle;$('source').href=app.source;$('source').textContent=app.sourceLabel;
  $('filters').innerHTML=app.filters.map(f=>`<label>${escapeHtml(f.label)}<select id="filter-${escapeHtml(f.key)}"><option value="">All</option>${[...new Set(data.map(r=>String(r[f.key])))].sort(f.sort||undefined).map(v=>`<option value="${escapeHtml(v)}">${escapeHtml(v)}</option>`).join('')}</select></label>`).join('')+'<button class="reset" id="reset">Reset filters</button>';
  app.filters.forEach(f=>$('filter-'+f.key).addEventListener('change',render));$('reset').onclick=()=>{app.filters.forEach(f=>$('filter-'+f.key).value='');render()};render()}
function render(){let rows=data.filter(r=>app.filters.every(f=>!$('filter-'+f.key).value||String(r[f.key])===$('filter-'+f.key).value));$('count').textContent=`${rows.length.toLocaleString()} ${app.unit} in selection`;
  $('cards').innerHTML=app.cards.map(c=>`<div class="card"><small>${escapeHtml(c.label)}</small><strong>${fmt(c.calc(rows),c.format)}</strong><span>${escapeHtml(c.note)}</span></div>`).join('');
  app.charts.forEach((c,i)=>{let groups=new Map;rows.forEach(r=>{let k=String(r[c.key]);if(!groups.has(k))groups.set(k,[]);groups.get(k).push(r)});let entries=[...groups].sort((a,b)=>c.sort?c.sort(a[0],b[0]):a[0].localeCompare(b[0],undefined,{numeric:true})).map(([k,v])=>[k,c.calc(v)]);$('chart-title-'+i).textContent=c.title;$('chart-desc-'+i).textContent=c.description;draw($('chart-'+i),entries,c.type,c.format)})}
function draw(el,entries,type,format){el.replaceChildren();const W=650,H=300,L=54,R=18,T=25,B=65,iw=W-L-R,ih=H-T-B;let svg=document.createElementNS(svgNS,'svg');svg.setAttribute('viewBox',`0 0 ${W} ${H}`);svg.setAttribute('role','img');svg.setAttribute('aria-label',entries.length?`${type} chart, ${entries.length} categories`:'No data');el.append(svg);
  function add(tag,attrs,text){let x=document.createElementNS(svgNS,tag);for(let [k,v] of Object.entries(attrs))x.setAttribute(k,v);if(text!==undefined)x.textContent=text;svg.append(x);return x}
  if(!entries.length){add('text',{x:W/2,y:H/2,'text-anchor':'middle'},'No data for this selection');return}let max=Math.max(format==='percent'?0.01:1,...entries.map(x=>x[1]));for(let j=0;j<=4;j++){let y=T+ih*(1-j/4);add('line',{x1:L,x2:W-R,y1:y,y2:y,class:'gridline'});add('text',{x:L-8,y:y+4,'text-anchor':'end'},fmt(max*j/4,format))}
  let step=iw/entries.length,pts=[];entries.forEach(([label,value],i)=>{let x=L+step*(i+.5),y=T+ih*(1-value/max);if(type==='bar'){let bar=add('rect',{x:x-step*.36,y,width:step*.72,height:T+ih-y,rx:3,class:'bar'});let tip=document.createElementNS(svgNS,'title');tip.textContent=`${label}: ${fmt(value,format)}`;bar.append(tip)}else pts.push([x,y,label,value]);if(entries.length<=16||i%Math.ceil(entries.length/12)===0){let t=add('text',{x,y:H-B+19,'text-anchor':'end',transform:`rotate(-35 ${x} ${H-B+19})`},label.length>15?label.slice(0,13)+'…':label)}});
  if(type==='line'){add('polyline',{points:pts.map(p=>p.slice(0,2).join(',')).join(' '),class:'line'});pts.forEach(([x,y,label,value])=>{let dot=add('circle',{cx:x,cy:y,r:4,class:'dot'});let tip=document.createElementNS(svgNS,'title');tip.textContent=`${label}: ${fmt(value,format)}`;dot.append(tip)})}}
init();
